version: "3"
services:
    web:
        build: .
        volumes: 
            - .:/app
        ports:
            - 8080:8080
        links:
            - redis
            - kafka
    redis:
        image: redis
        volumes: 
            - ./redis:/redis
        ports:
            - 6379:6379

    kafka:
        image: lalchandrajak05/kafka:Go        
        volumes:
            - ./kafka:/kafka
        ports:
            - "9092:9092"
             
